defaults:
  branches:
  - release-1.10
  repo-allowlist:
  - release-builder
org: istio
repo: release-builder
transforms:
- job-allowlist:
  - lint_release-builder_release-1.10
  - lint_release-builder_release-1.10_postsubmit
  - test_release-builder_release-1.10
  - test_release-builder_release-1.10_postsubmit
  - gencheck_release-builder_release-1.10
  - gencheck_release-builder_release-1.10_postsubmit
  job-type:
  - presubmit
  - postsubmit
- env:
    GCS_BUCKET: istio-private-prerelease/prerelease
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
  job-allowlist:
  - build-warning_release-builder_release-1.10
  job-type:
  - presubmit
- env:
    GCS_BUCKET: istio-private-prerelease/prerelease
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
  job-allowlist:
  - build-release_release-builder_release-1.10_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-ssh: "true"
    preset-override-deps: release-1.10-release
    preset-override-envoy: "true"
